### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DaDevGuy** [AIPTU/BlockReplacer#23]
```yaml
---
# Do not change this (Only for internal use)!
config-version: 1.5

# The time in seconds when the block will be replaced with the previous block.
cooldown: 10

# Dropped items will be automatically added to the player's inventory.
# If the player inventory is full, the item will automatically be dropped near the player.
auto-pickup: true

# Default block to use as a replacement.
# If the block has meta, you can use the format "id:meta".
default-replace: "bedrock"
# List of blocks to be replaced.
# If the block has a meta, you can use the format "id:meta".
list-blocks:
  - "cobblestone=stone" # Cobblestone will be replaced to stone.
  - "dirt=grass"
  - "oak_log=oak_log:1"
  - "coal_ore" # It will be replaced to the default replacement block.
  - "diamond_ore"
  - "gold_ore"
  - "iron_ore"
  - "wheat_block=air"
  - "pumpkin=air"
  - "beetroot=air"

# Set this to true if you want to use the blacklisted-worlds settings.
# If both enable-world-blacklist and disable-world-blacklist are set to the same setting,
# block will be replaced for all worlds.
enable-world-blacklist: true
# If enable-world-blacklist is set to true, block will be replaced for all worlds,
# except the worlds mentioned here.
blacklisted-worlds:
  - "Island"

# Set this to true if you want to use the whitelisted-worlds settings.
# If both enable-world-blacklist and disable-world-blacklist are set to the same setting,
# block will not be replaced for all worlds.
enable-world-whitelist: true
# If enable-world-whitelist is set to true, block will not be replaced for all worlds,
# except the worlds mentioned here.
whitelisted-worlds:
  - "mine"
  - "Hypixel - Skyblock Hub"
...
---
# Do not change this (Only for internal use)!
config-version: 1.5

# The time in seconds when the block will be replaced with the previous block.
cooldown: 10

# Dropped items will be automatically added to the player's inventory.
# If the player inventory is full, the item will automatically be dropped near the player.
auto-pickup: true

# Default block to use as a replacement.
# If the block has meta, you can use the format "id:meta".
default-replace: "bedrock"
# List of blocks to be replaced.
# If the block has a meta, you can use the format "id:meta".
list-blocks:
  - "cobblestone=stone" # Cobblestone will be replaced to stone.
  - "dirt=grass"
  - "oak_log=oak_log:1"
  - "coal_ore" # It will be replaced to the default replacement block.
  - "diamond_ore"
  - "gold_ore"
  - "iron_ore"
  - "wheat_block=air"
  - "pumpkin=air"
  - "beetroot=air"

# Set this to true if you want to use the blacklisted-worlds settings.
# If both enable-world-blacklist and disable-world-blacklist are set to the same setting,
# block will be replaced for all worlds.
enable-world-blacklist: false
# If enable-world-blacklist is set to true, block will be replaced for all worlds,
# except the worlds mentioned here.
blacklisted-worlds:
- ""
# Set this to true if you want to use the whitelisted-worlds settings.
# If both enable-world-blacklist and disable-world-blacklist are set to the same setting,
# block will not be replaced for all worlds.
enable-world-whitelist: true
# If enable-world-whitelist is set to true, block will not be replaced for all worlds,
# except the worlds mentioned here.
whitelisted-worlds:
  - "mine"
  - "Hypixel - Skyblock Hub"
...
```
 so i have enabled block replacement for only 2 worlds `mine` and `Hypixel - Skyblock Hub` But Its Replacing For all worlds such as islands.
